version: "3"
services:
  postgresdb:
    container_name: postgresdb
    image: library/postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: springuser1
      POSTGRES_PASSWORD: springpassword1
      POSTGRES_DB: library
#    volumes:
#      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    container_name: backend
    image: 32-docker-backend:latest
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
    networks:
      - backend
      - frontend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/library
      SPRING_DATASOURCE_USERNAME: springuser1
      SPRING_DATASOURCE_PASSWORD: springpassword1

  frontend:
    container_name: frontend
    image: library/nginx:1.17.1-alpine
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./build:/usr/share/nginx/html
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - frontend


networks:
  frontend:
  backend:

#volumes:
#  db-data: