server:
  port: 8003

spring:
  application:
    name: zuul-service-gateway

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 15
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
zuul:
  routes:
    core: /core/**
  sensitive-headers:
    - Cookie
    - Set-Cookie