spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/library

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.shurupov.spring.springdatamongodb.mongock.changelog
