spring:
  data:
    mongodb:
      database: library

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
