spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: springuser
    password: springpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: never

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true

liquibase:
  enabled: true
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/library
  user: springuser
  password: springpassword

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,shutdown
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    root: INFO
    ru.otus: DEBUG
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: logs/app.log