spring:
  application:
    name: eureka-discovery-server

server:
  port: 8001

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 15000
    registry-sync-retries: 0
    max-threads-for-peer-replication: 0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8001/eureka
